excluded:
  - Sources/HopsProto
  - .build

disabled_rules:
  - blanket_disable_command

line_length: 120
type_body_length:
  warning: 350
  error: 500
function_body_length:
  warning: 50
  error: 100
file_length:
  warning: 400
  error: 600

identifier_name:
  min_length:
    warning: 2
    error: 1
