//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: proto/hops.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Hops_HopsServiceClient`, then call methods of this protocol to make API calls.
public protocol Hops_HopsServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Hops_HopsServiceClientInterceptorFactoryProtocol? { get }

  func runSandbox(
    _ request: Hops_RunRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Hops_RunRequest, Hops_RunResponse>

  func runSandboxStreaming(
    _ request: Hops_RunRequest,
    callOptions: CallOptions?,
    handler: @escaping (Hops_OutputChunk) -> Void
  ) -> ServerStreamingCall<Hops_RunRequest, Hops_OutputChunk>

  func stopSandbox(
    _ request: Hops_StopRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Hops_StopRequest, Hops_StopResponse>

  func listSandboxes(
    _ request: Hops_ListRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Hops_ListRequest, Hops_ListResponse>

  func getStatus(
    _ request: Hops_StatusRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Hops_StatusRequest, Hops_SandboxStatus>

  func getDaemonStatus(
    _ request: Hops_DaemonStatusRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Hops_DaemonStatusRequest, Hops_DaemonStatusResponse>
}

extension Hops_HopsServiceClientProtocol {
  public var serviceName: String {
    return "hops.HopsService"
  }

  /// Unary call to RunSandbox
  ///
  /// - Parameters:
  ///   - request: Request to send to RunSandbox.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func runSandbox(
    _ request: Hops_RunRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Hops_RunRequest, Hops_RunResponse> {
    return self.makeUnaryCall(
      path: Hops_HopsServiceClientMetadata.Methods.runSandbox.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRunSandboxInterceptors() ?? []
    )
  }

  /// Server streaming call to RunSandboxStreaming
  ///
  /// - Parameters:
  ///   - request: Request to send to RunSandboxStreaming.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  public func runSandboxStreaming(
    _ request: Hops_RunRequest,
    callOptions: CallOptions? = nil,
    handler: @escaping (Hops_OutputChunk) -> Void
  ) -> ServerStreamingCall<Hops_RunRequest, Hops_OutputChunk> {
    return self.makeServerStreamingCall(
      path: Hops_HopsServiceClientMetadata.Methods.runSandboxStreaming.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRunSandboxStreamingInterceptors() ?? [],
      handler: handler
    )
  }

  /// Unary call to StopSandbox
  ///
  /// - Parameters:
  ///   - request: Request to send to StopSandbox.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func stopSandbox(
    _ request: Hops_StopRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Hops_StopRequest, Hops_StopResponse> {
    return self.makeUnaryCall(
      path: Hops_HopsServiceClientMetadata.Methods.stopSandbox.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStopSandboxInterceptors() ?? []
    )
  }

  /// Unary call to ListSandboxes
  ///
  /// - Parameters:
  ///   - request: Request to send to ListSandboxes.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func listSandboxes(
    _ request: Hops_ListRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Hops_ListRequest, Hops_ListResponse> {
    return self.makeUnaryCall(
      path: Hops_HopsServiceClientMetadata.Methods.listSandboxes.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListSandboxesInterceptors() ?? []
    )
  }

  /// Unary call to GetStatus
  ///
  /// - Parameters:
  ///   - request: Request to send to GetStatus.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getStatus(
    _ request: Hops_StatusRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Hops_StatusRequest, Hops_SandboxStatus> {
    return self.makeUnaryCall(
      path: Hops_HopsServiceClientMetadata.Methods.getStatus.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetStatusInterceptors() ?? []
    )
  }

  /// Unary call to GetDaemonStatus
  ///
  /// - Parameters:
  ///   - request: Request to send to GetDaemonStatus.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getDaemonStatus(
    _ request: Hops_DaemonStatusRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Hops_DaemonStatusRequest, Hops_DaemonStatusResponse> {
    return self.makeUnaryCall(
      path: Hops_HopsServiceClientMetadata.Methods.getDaemonStatus.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetDaemonStatusInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Hops_HopsServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Hops_HopsServiceNIOClient")
public final class Hops_HopsServiceClient: Hops_HopsServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Hops_HopsServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Hops_HopsServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the hops.HopsService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Hops_HopsServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Hops_HopsServiceNIOClient: Hops_HopsServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Hops_HopsServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the hops.HopsService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Hops_HopsServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Hops_HopsServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Hops_HopsServiceClientInterceptorFactoryProtocol? { get }

  func makeRunSandboxCall(
    _ request: Hops_RunRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Hops_RunRequest, Hops_RunResponse>

  func makeRunSandboxStreamingCall(
    _ request: Hops_RunRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncServerStreamingCall<Hops_RunRequest, Hops_OutputChunk>

  func makeStopSandboxCall(
    _ request: Hops_StopRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Hops_StopRequest, Hops_StopResponse>

  func makeListSandboxesCall(
    _ request: Hops_ListRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Hops_ListRequest, Hops_ListResponse>

  func makeGetStatusCall(
    _ request: Hops_StatusRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Hops_StatusRequest, Hops_SandboxStatus>

  func makeGetDaemonStatusCall(
    _ request: Hops_DaemonStatusRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Hops_DaemonStatusRequest, Hops_DaemonStatusResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Hops_HopsServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Hops_HopsServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Hops_HopsServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeRunSandboxCall(
    _ request: Hops_RunRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Hops_RunRequest, Hops_RunResponse> {
    return self.makeAsyncUnaryCall(
      path: Hops_HopsServiceClientMetadata.Methods.runSandbox.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRunSandboxInterceptors() ?? []
    )
  }

  public func makeRunSandboxStreamingCall(
    _ request: Hops_RunRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncServerStreamingCall<Hops_RunRequest, Hops_OutputChunk> {
    return self.makeAsyncServerStreamingCall(
      path: Hops_HopsServiceClientMetadata.Methods.runSandboxStreaming.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRunSandboxStreamingInterceptors() ?? []
    )
  }

  public func makeStopSandboxCall(
    _ request: Hops_StopRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Hops_StopRequest, Hops_StopResponse> {
    return self.makeAsyncUnaryCall(
      path: Hops_HopsServiceClientMetadata.Methods.stopSandbox.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStopSandboxInterceptors() ?? []
    )
  }

  public func makeListSandboxesCall(
    _ request: Hops_ListRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Hops_ListRequest, Hops_ListResponse> {
    return self.makeAsyncUnaryCall(
      path: Hops_HopsServiceClientMetadata.Methods.listSandboxes.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListSandboxesInterceptors() ?? []
    )
  }

  public func makeGetStatusCall(
    _ request: Hops_StatusRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Hops_StatusRequest, Hops_SandboxStatus> {
    return self.makeAsyncUnaryCall(
      path: Hops_HopsServiceClientMetadata.Methods.getStatus.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetStatusInterceptors() ?? []
    )
  }

  public func makeGetDaemonStatusCall(
    _ request: Hops_DaemonStatusRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Hops_DaemonStatusRequest, Hops_DaemonStatusResponse> {
    return self.makeAsyncUnaryCall(
      path: Hops_HopsServiceClientMetadata.Methods.getDaemonStatus.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetDaemonStatusInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Hops_HopsServiceAsyncClientProtocol {
  public func runSandbox(
    _ request: Hops_RunRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Hops_RunResponse {
    return try await self.performAsyncUnaryCall(
      path: Hops_HopsServiceClientMetadata.Methods.runSandbox.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRunSandboxInterceptors() ?? []
    )
  }

  public func runSandboxStreaming(
    _ request: Hops_RunRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Hops_OutputChunk> {
    return self.performAsyncServerStreamingCall(
      path: Hops_HopsServiceClientMetadata.Methods.runSandboxStreaming.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRunSandboxStreamingInterceptors() ?? []
    )
  }

  public func stopSandbox(
    _ request: Hops_StopRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Hops_StopResponse {
    return try await self.performAsyncUnaryCall(
      path: Hops_HopsServiceClientMetadata.Methods.stopSandbox.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStopSandboxInterceptors() ?? []
    )
  }

  public func listSandboxes(
    _ request: Hops_ListRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Hops_ListResponse {
    return try await self.performAsyncUnaryCall(
      path: Hops_HopsServiceClientMetadata.Methods.listSandboxes.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListSandboxesInterceptors() ?? []
    )
  }

  public func getStatus(
    _ request: Hops_StatusRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Hops_SandboxStatus {
    return try await self.performAsyncUnaryCall(
      path: Hops_HopsServiceClientMetadata.Methods.getStatus.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetStatusInterceptors() ?? []
    )
  }

  public func getDaemonStatus(
    _ request: Hops_DaemonStatusRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Hops_DaemonStatusResponse {
    return try await self.performAsyncUnaryCall(
      path: Hops_HopsServiceClientMetadata.Methods.getDaemonStatus.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetDaemonStatusInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Hops_HopsServiceAsyncClient: Hops_HopsServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Hops_HopsServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Hops_HopsServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Hops_HopsServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'runSandbox'.
  func makeRunSandboxInterceptors() -> [ClientInterceptor<Hops_RunRequest, Hops_RunResponse>]

  /// - Returns: Interceptors to use when invoking 'runSandboxStreaming'.
  func makeRunSandboxStreamingInterceptors() -> [ClientInterceptor<Hops_RunRequest, Hops_OutputChunk>]

  /// - Returns: Interceptors to use when invoking 'stopSandbox'.
  func makeStopSandboxInterceptors() -> [ClientInterceptor<Hops_StopRequest, Hops_StopResponse>]

  /// - Returns: Interceptors to use when invoking 'listSandboxes'.
  func makeListSandboxesInterceptors() -> [ClientInterceptor<Hops_ListRequest, Hops_ListResponse>]

  /// - Returns: Interceptors to use when invoking 'getStatus'.
  func makeGetStatusInterceptors() -> [ClientInterceptor<Hops_StatusRequest, Hops_SandboxStatus>]

  /// - Returns: Interceptors to use when invoking 'getDaemonStatus'.
  func makeGetDaemonStatusInterceptors() -> [ClientInterceptor<Hops_DaemonStatusRequest, Hops_DaemonStatusResponse>]
}

public enum Hops_HopsServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "HopsService",
    fullName: "hops.HopsService",
    methods: [
      Hops_HopsServiceClientMetadata.Methods.runSandbox,
      Hops_HopsServiceClientMetadata.Methods.runSandboxStreaming,
      Hops_HopsServiceClientMetadata.Methods.stopSandbox,
      Hops_HopsServiceClientMetadata.Methods.listSandboxes,
      Hops_HopsServiceClientMetadata.Methods.getStatus,
      Hops_HopsServiceClientMetadata.Methods.getDaemonStatus,
    ]
  )

  public enum Methods {
    public static let runSandbox = GRPCMethodDescriptor(
      name: "RunSandbox",
      path: "/hops.HopsService/RunSandbox",
      type: GRPCCallType.unary
    )

    public static let runSandboxStreaming = GRPCMethodDescriptor(
      name: "RunSandboxStreaming",
      path: "/hops.HopsService/RunSandboxStreaming",
      type: GRPCCallType.serverStreaming
    )

    public static let stopSandbox = GRPCMethodDescriptor(
      name: "StopSandbox",
      path: "/hops.HopsService/StopSandbox",
      type: GRPCCallType.unary
    )

    public static let listSandboxes = GRPCMethodDescriptor(
      name: "ListSandboxes",
      path: "/hops.HopsService/ListSandboxes",
      type: GRPCCallType.unary
    )

    public static let getStatus = GRPCMethodDescriptor(
      name: "GetStatus",
      path: "/hops.HopsService/GetStatus",
      type: GRPCCallType.unary
    )

    public static let getDaemonStatus = GRPCMethodDescriptor(
      name: "GetDaemonStatus",
      path: "/hops.HopsService/GetDaemonStatus",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Hops_HopsServiceProvider: CallHandlerProvider {
  var interceptors: Hops_HopsServiceServerInterceptorFactoryProtocol? { get }

  func runSandbox(request: Hops_RunRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Hops_RunResponse>

  func runSandboxStreaming(request: Hops_RunRequest, context: StreamingResponseCallContext<Hops_OutputChunk>) -> EventLoopFuture<GRPCStatus>

  func stopSandbox(request: Hops_StopRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Hops_StopResponse>

  func listSandboxes(request: Hops_ListRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Hops_ListResponse>

  func getStatus(request: Hops_StatusRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Hops_SandboxStatus>

  func getDaemonStatus(request: Hops_DaemonStatusRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Hops_DaemonStatusResponse>
}

extension Hops_HopsServiceProvider {
  public var serviceName: Substring {
    return Hops_HopsServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "RunSandbox":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Hops_RunRequest>(),
        responseSerializer: ProtobufSerializer<Hops_RunResponse>(),
        interceptors: self.interceptors?.makeRunSandboxInterceptors() ?? [],
        userFunction: self.runSandbox(request:context:)
      )

    case "RunSandboxStreaming":
      return ServerStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Hops_RunRequest>(),
        responseSerializer: ProtobufSerializer<Hops_OutputChunk>(),
        interceptors: self.interceptors?.makeRunSandboxStreamingInterceptors() ?? [],
        userFunction: self.runSandboxStreaming(request:context:)
      )

    case "StopSandbox":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Hops_StopRequest>(),
        responseSerializer: ProtobufSerializer<Hops_StopResponse>(),
        interceptors: self.interceptors?.makeStopSandboxInterceptors() ?? [],
        userFunction: self.stopSandbox(request:context:)
      )

    case "ListSandboxes":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Hops_ListRequest>(),
        responseSerializer: ProtobufSerializer<Hops_ListResponse>(),
        interceptors: self.interceptors?.makeListSandboxesInterceptors() ?? [],
        userFunction: self.listSandboxes(request:context:)
      )

    case "GetStatus":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Hops_StatusRequest>(),
        responseSerializer: ProtobufSerializer<Hops_SandboxStatus>(),
        interceptors: self.interceptors?.makeGetStatusInterceptors() ?? [],
        userFunction: self.getStatus(request:context:)
      )

    case "GetDaemonStatus":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Hops_DaemonStatusRequest>(),
        responseSerializer: ProtobufSerializer<Hops_DaemonStatusResponse>(),
        interceptors: self.interceptors?.makeGetDaemonStatusInterceptors() ?? [],
        userFunction: self.getDaemonStatus(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Hops_HopsServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Hops_HopsServiceServerInterceptorFactoryProtocol? { get }

  func runSandbox(
    request: Hops_RunRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Hops_RunResponse

  func runSandboxStreaming(
    request: Hops_RunRequest,
    responseStream: GRPCAsyncResponseStreamWriter<Hops_OutputChunk>,
    context: GRPCAsyncServerCallContext
  ) async throws

  func stopSandbox(
    request: Hops_StopRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Hops_StopResponse

  func listSandboxes(
    request: Hops_ListRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Hops_ListResponse

  func getStatus(
    request: Hops_StatusRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Hops_SandboxStatus

  func getDaemonStatus(
    request: Hops_DaemonStatusRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Hops_DaemonStatusResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Hops_HopsServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Hops_HopsServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Hops_HopsServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Hops_HopsServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "RunSandbox":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Hops_RunRequest>(),
        responseSerializer: ProtobufSerializer<Hops_RunResponse>(),
        interceptors: self.interceptors?.makeRunSandboxInterceptors() ?? [],
        wrapping: { try await self.runSandbox(request: $0, context: $1) }
      )

    case "RunSandboxStreaming":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Hops_RunRequest>(),
        responseSerializer: ProtobufSerializer<Hops_OutputChunk>(),
        interceptors: self.interceptors?.makeRunSandboxStreamingInterceptors() ?? [],
        wrapping: { try await self.runSandboxStreaming(request: $0, responseStream: $1, context: $2) }
      )

    case "StopSandbox":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Hops_StopRequest>(),
        responseSerializer: ProtobufSerializer<Hops_StopResponse>(),
        interceptors: self.interceptors?.makeStopSandboxInterceptors() ?? [],
        wrapping: { try await self.stopSandbox(request: $0, context: $1) }
      )

    case "ListSandboxes":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Hops_ListRequest>(),
        responseSerializer: ProtobufSerializer<Hops_ListResponse>(),
        interceptors: self.interceptors?.makeListSandboxesInterceptors() ?? [],
        wrapping: { try await self.listSandboxes(request: $0, context: $1) }
      )

    case "GetStatus":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Hops_StatusRequest>(),
        responseSerializer: ProtobufSerializer<Hops_SandboxStatus>(),
        interceptors: self.interceptors?.makeGetStatusInterceptors() ?? [],
        wrapping: { try await self.getStatus(request: $0, context: $1) }
      )

    case "GetDaemonStatus":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Hops_DaemonStatusRequest>(),
        responseSerializer: ProtobufSerializer<Hops_DaemonStatusResponse>(),
        interceptors: self.interceptors?.makeGetDaemonStatusInterceptors() ?? [],
        wrapping: { try await self.getDaemonStatus(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

public protocol Hops_HopsServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'runSandbox'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeRunSandboxInterceptors() -> [ServerInterceptor<Hops_RunRequest, Hops_RunResponse>]

  /// - Returns: Interceptors to use when handling 'runSandboxStreaming'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeRunSandboxStreamingInterceptors() -> [ServerInterceptor<Hops_RunRequest, Hops_OutputChunk>]

  /// - Returns: Interceptors to use when handling 'stopSandbox'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeStopSandboxInterceptors() -> [ServerInterceptor<Hops_StopRequest, Hops_StopResponse>]

  /// - Returns: Interceptors to use when handling 'listSandboxes'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeListSandboxesInterceptors() -> [ServerInterceptor<Hops_ListRequest, Hops_ListResponse>]

  /// - Returns: Interceptors to use when handling 'getStatus'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetStatusInterceptors() -> [ServerInterceptor<Hops_StatusRequest, Hops_SandboxStatus>]

  /// - Returns: Interceptors to use when handling 'getDaemonStatus'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetDaemonStatusInterceptors() -> [ServerInterceptor<Hops_DaemonStatusRequest, Hops_DaemonStatusResponse>]
}

public enum Hops_HopsServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "HopsService",
    fullName: "hops.HopsService",
    methods: [
      Hops_HopsServiceServerMetadata.Methods.runSandbox,
      Hops_HopsServiceServerMetadata.Methods.runSandboxStreaming,
      Hops_HopsServiceServerMetadata.Methods.stopSandbox,
      Hops_HopsServiceServerMetadata.Methods.listSandboxes,
      Hops_HopsServiceServerMetadata.Methods.getStatus,
      Hops_HopsServiceServerMetadata.Methods.getDaemonStatus,
    ]
  )

  public enum Methods {
    public static let runSandbox = GRPCMethodDescriptor(
      name: "RunSandbox",
      path: "/hops.HopsService/RunSandbox",
      type: GRPCCallType.unary
    )

    public static let runSandboxStreaming = GRPCMethodDescriptor(
      name: "RunSandboxStreaming",
      path: "/hops.HopsService/RunSandboxStreaming",
      type: GRPCCallType.serverStreaming
    )

    public static let stopSandbox = GRPCMethodDescriptor(
      name: "StopSandbox",
      path: "/hops.HopsService/StopSandbox",
      type: GRPCCallType.unary
    )

    public static let listSandboxes = GRPCMethodDescriptor(
      name: "ListSandboxes",
      path: "/hops.HopsService/ListSandboxes",
      type: GRPCCallType.unary
    )

    public static let getStatus = GRPCMethodDescriptor(
      name: "GetStatus",
      path: "/hops.HopsService/GetStatus",
      type: GRPCCallType.unary
    )

    public static let getDaemonStatus = GRPCMethodDescriptor(
      name: "GetDaemonStatus",
      path: "/hops.HopsService/GetDaemonStatus",
      type: GRPCCallType.unary
    )
  }
}
